### ISSUE TITLE
Implement first version of GraphQL server

### ISSUE THREAD

**Issue by Konard** [linksplatform/Data.Doublets.Gql#1]
10000 RUB reward can be claimed by anyone who completes this task.

This task is continuation of https://github.com/Konard/LinksPlatform/issues/571

**Comment by FirstAfterGod2501** [comment]
i took this task

**Comment by Konard** [comment]
![IMG_20210820_132606](https://user-images.githubusercontent.com/1431904/130221111-31731b7a-8b30-4284-ada5-52646726a900.jpg)

**Comment by Konard** [comment]
https://hasura.io/docs/latest/graphql/core/guides/export-graphql-schema.html - tools for schema export

**Comment by Konard** [comment]
Rewards are:
6000 RUB for @FirstAfterGod2501
4000 RUB for @FreePhoenix888
